"""Add responsible_user_id to Ticket

Revision ID: a182a0a0abd4
Revises: 
Create Date: 2025-10-30 20:53:23.318952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182a0a0abd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ticket_responsible_user_id', 'user', ['responsible_user_id'], ['id'])
        batch_op.drop_column('responsible_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('responsible_user_id')

    # ### end Alembic commands ###
