"""Add is_internal to TicketComment

Revision ID: d68651f2e55d
Revises: a182a0a0abd4
Create Date: 2025-11-03 19:43:41.009709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68651f2e55d'
down_revision = 'a182a0a0abd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comment', schema=None) as batch_op:
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###
